### ISSUE TITLE
iosevka-generate misses dependency `inflection`

### ISSUE THREAD

**Issue by jfrankenau** [OJFord/homebrew-formulae#4]
The `iosevka-generate` formula is missing the Python module `inflection` as a resource if I am not mistaken.

```
Traceback (most recent call last):
  File "/usr/local/bin/iosevka-generate", line 12, in <module>
    import inflection
ModuleNotFoundError: No module named 'inflection'
```

**Comment by OJFord** [comment]
Thanks for the report, it certainly seems to be!

I suppose I installed it (system-wide) via the `requirements.txt` while working on it (if it wasn't already installed) and so missed the error on creating the formula. Will look to fix, thanks.
