### ISSUE TITLE
Java dependency format `depends_on :java` was disabled

### ISSUE THREAD

**Issue by strobh** [OJFord/homebrew-formulae#6]
Homebrew has deprecated and disabled the java dependency format `depends_on :java`
(see Homebrew/brew#9194) resulting in the following error:

```
Error: Failed to import: /usr/local/Homebrew/Library/Taps/ojford/homebrew-formulae/ltsa.rb
ltsa: Calling depends_on :java is disabled! Use "depends_on "openjdk@11", "depends_on "openjdk@8" or "depends_on "openjdk" instead
```

I have already created a PR (#5) that tries to solve the problem by explicitly using "openjdk@8" as dependency, but I haven't tested whether it works yet.

**Comment by OJFord** [comment]
Thank you! Closed via #5
